### ISSUE TITLE
BUG : Add same contract twice cause an server error

### ISSUE THREAD

**Issue by quentin-burg** [marigold-dev/gas-station#21]
- Add a contract which already added on Gas Station
- => Error 500 because contract address must be unique on database

**Comment by quentin-burg** [comment]
See https://github.com/marigold-dev/gas-station/pull/27

**Comment by aguillon** [comment]
Is this a good behaviour though? We're doing it mostly because we haven't defined what we should do when several users are ready to pay for a given contract, but we could relax the current approach and just take the vault with the more credits. FWIW, it has been reported as surprising by some users (1) that we just refuse a contract which is already subsidized.

**Comment by quentin-burg** [comment]
Done on staging
